# Generated by Django 5.0.1 on 2024-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at_remote', models.DateTimeField(auto_now_add=True)),
                ('updated_at_local', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
