# Generated by Django 5.0.1 on 2024-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_epub_url_book_epub_id_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(null=True),
        ),
    ]
