# Generated by Django 5.0.3 on 2024-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(default=None, null=True),
        ),
    ]
