# Generated by Django 5.0.4 on 2024-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='img_url',
            field=models.CharField(max_length=400),
        ),
    ]
