# Generated by Django 5.0.3 on 2024-04-20 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=2)),
                ('word_1', models.CharField(max_length=200)),
                ('word_2', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortugueseVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('present_eu', models.CharField(default=None, max_length=50, null=True)),
                ('present_ele', models.CharField(default=None, max_length=50, null=True)),
                ('present_nos', models.CharField(default=None, max_length=50, null=True)),
                ('present_eles', models.CharField(default=None, max_length=50, null=True)),
                ('preterite_eu', models.CharField(default=None, max_length=50, null=True)),
                ('preterite_ele', models.CharField(default=None, max_length=50, null=True)),
                ('preterite_nos', models.CharField(default=None, max_length=50, null=True)),
                ('preterite_eles', models.CharField(default=None, max_length=50, null=True)),
                ('imperfect_eu', models.CharField(default=None, max_length=50, null=True)),
                ('imperfect_ele', models.CharField(default=None, max_length=50, null=True)),
                ('imperfect_nos', models.CharField(default=None, max_length=50, null=True)),
                ('imperfect_eles', models.CharField(default=None, max_length=50, null=True)),
                ('future_eu', models.CharField(default=None, max_length=50, null=True)),
                ('future_ele', models.CharField(default=None, max_length=50, null=True)),
                ('future_nos', models.CharField(default=None, max_length=50, null=True)),
                ('future_eles', models.CharField(default=None, max_length=50, null=True)),
                ('conditional_eu', models.CharField(default=None, max_length=50, null=True)),
                ('conditional_ele', models.CharField(default=None, max_length=50, null=True)),
                ('conditional_nos', models.CharField(default=None, max_length=50, null=True)),
                ('conditional_eles', models.CharField(default=None, max_length=50, null=True)),
                ('subjunctive_eu', models.CharField(default=None, max_length=50, null=True)),
                ('subjunctive_ele', models.CharField(default=None, max_length=50, null=True)),
                ('subjunctive_nos', models.CharField(default=None, max_length=50, null=True)),
                ('subjunctive_eles', models.CharField(default=None, max_length=50, null=True)),
                ('past_participle', models.CharField(default=None, max_length=50, null=True)),
                ('gerund', models.CharField(default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocab')),
            ],
        ),
    ]
