# Generated by Django 5.0.3 on 2024-04-20 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_portfolio', models.BooleanField(default=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(default=None, null=True)),
                ('order_price', models.FloatField(default=None, null=True)),
                ('volume', models.IntegerField(default=None, null=True)),
                ('buy_recommendation', models.BooleanField(default=False)),
                ('today', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
